### ISSUE TITLE
Github likes to queue the build... for a while.

### ISSUE THREAD

**Issue by lightnin** [dr-matt-smith/pandoc-thesis-template#2]
Hi - and thanks for taking the time and trouble to share this! 

Just an FYI that at least for me, github is queuing the build instead of doing it immediately. I'm at 20 minutes since my last push and it has yet to start. It's possible they are low prioritizing me as I don't give 'em any money or have special status. Perhaps they run through your builds faster because you do? 

Anyhow - just thought I'd mention it so you are aware.

**Comment by lightnin** [comment]
Hmm, it's hard not to believe this delay isn't the result of some sort of new enshitification (https://pluralistic.net/2023/01/21/potemkin-ai/#hey-guys)  ploy on the part of Microsoft. Perhaps the old Readme with instructions for local builds should be dusted off? 
<img width="1189" alt="Screenshot 2023-05-21 at 14 30 08" src="https://github.com/dr-matt-smith/pandoc-thesis-template/assets/1538027/55a6fc87-9889-4e40-bd50-b5dafc18cd7b">

**Comment by dr-matt-smith** [comment]
hi there

it's hanging for me too (10 minutes and counting) - it always used to run in 30-40 seconds

- if PDF generation from Github Actions can't be relied on any more it makes this project pretty useless!
- (I generally use Pandoc on my own machine, but I created this repo to my students didn't have to set up all that Pandoc/LaTeX etc. technology stack - I want them to focus on writing their thesis not the typesetting and PDF generation ...)

I've contacted Github Education - I and my students use free Github resources through their education programme for universities

I'll post again here once I hear back from them to see what is happening ...

.. matt ..

**Comment by lightnin** [comment]
Thanks for investigating, Matt! There don't appear to be any published outages on this page: https://www.githubstatus.com/ 
It's not so easy to debug based on the limited feedback I'm getting from the interface. But let's see what they say. :) 
I'm at 3 hours 37 minutes and counting... Are the instructions in the old readme still fairly accurate as far as you know? Maybe I'll try them out.

**Comment by lightnin** [comment]
And... just got a note saying my build failed. :) That was a long wait.
I've used your Readme-old to get local builds working, so no more waiting for old Github for me. Thanks a million for sharing your very helpful code! I do hope for your student's sake that Github fixes this....

**Comment by dr-matt-smith** [comment]
I got a fail notification today, with a note to a deprecation of Ubuntu-18.04
Recommending updating to Ubuntu-22.04

I made that change to the actions yaml and it seems to have passed 
- but I'm on my phone and can't see where the built PDF is ... I'll check when I've time at my computer next 

But it's looking hopeful that things may be due to the deprecating of Ubuntu-18 and not a shitification by Github by not giving resources to runners 

But I'm surprised dependabot or some agent didn't highlight the deprecated virtual machine configuration before now 

However, I was not able to email GitHub education the way I used to - I got redirected to the mess of support pages and forums 
- organisations these days just don't want to actually engage with users - I guess Microsoft wants to spend its billions of other things that communicating with lecturers who were encouraging their students to use GitHub ...

**Comment by dr-matt-smith** [comment]
it seems a runner is not picked up if there are issues with the actions YAML contents
ubuntu 18 was deprecated / also Node 12 issue (see last few commits...)

- I couldn't get latest-ubuntu to work, so currently ubuntu-22.04, and assume this will need updating in a few years
- I couldn't get docker://pandoc/latex to work, so currently docker://pandoc/latex:2.9, and assume this will need updating in a few years
- I couldn't get actions/checkout@main to work, so currently using actions/checkout@v3, and assume this will need updating in a few years

but seems to be picking up runners in less than a minute now - so hopefully good enough for reliable thesis generation 

.. matt ..

refs:
- [Node12/16 thing:](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/)

- [Ubuntu 22 thing:](https://github.com/actions/runner-images/issues/6399)

**Comment by lightnin** [comment]
Great that you got to the bottom of it! But have the people at Microsoft Github never heard of error messages? If they have code that stops runners from picking things up, how hard can it be to have that code tell the user why? 
Anyhow - thanks for your help and I'll leave it to you to close this. And I'll just mention that I've had good luck with Gitlab lately. A bit less polish but very good overall, and they are hosting my open source project to teach kids about sustainability for free. :)

**Comment by dr-matt-smith** [comment]
> But have the people at Microsoft Github never heard of error messages?

yes they could have made it a lot easier to track down the problem!

> And I'll just mention that I've had good luck with Gitlab
thanks  - I'll look at Gitlab again
- when I contacted them some years ago they simply wouldn't offer important stuff for free for my university students, and my rule is that if it costs money I don't use it, since half my students won't / can't pay for any extra on top of fees / accommodation / buying a laptop etc. 

when it works, Github Actions, Codespaces etc. give a great free introduction to development stuff for students
- but I'm still waiting for any reply to the issue we just resolved with Actions - not a good sign about the way they are moving (I spent 30mins in their forums yesterday - lots of frustrated people with unanswered stuff - I'm guessing their support team has been reduced so they've tried to move all support to forums so they think they can get away with less staff..... it'll cost them in the long run ...)

I think any company that does't give decent stuff to free to students is crazy, since once they working they'll want to use the same too
(Jetbrains is a good example - I use all their tools for C#/PHP/Python etc. and encourage student to use them too - and I'm sure a bunch then stick with those tools when they go pro ...)

regards .. matt ..
